"""Pilot evidence report — the artifact a design partner takes to their stakeholders.

Runs the MVP workflows through the governed runtime (synthetic data, local route)
plus a refusal scenario, measures the things a pilot must prove, scores them
against default acceptance gates, and writes `pilot-report.md`.

Usage:  make pilot-report   (or)   python scripts/pilot_report.py
Exit 0 = all acceptance gates passed.
"""
from __future__ import annotations

import sys
from pathlib import Path

from florence_core.events import EventLog, NullSink
from florence_core.observability import POINT_OF_CARE_BUDGET_MS, LatencyBudget
from florence_core.schemas import EDENADecision, RequesterContext, Signal
from florence_core.state import InMemoryRepository
from florence_core.workflows import AutoApproveReviewer, Runtime, load_agent, load_workflow
from florence_edena import EdenaClient
from florence_model_router import ModelRouter

ROOT = Path(__file__).resolve().parents[1]
EXAMPLES = ROOT / "examples"

# (example dir, signal_type, data_classification)
WORKFLOWS = [
    ("icu_handoff", "icu_handoff_needed", "phi_local"),
    ("patient_education", "patient_education_needed", "phi_local"),
    ("policy_retrieval", "policy_question", "internal"),
    ("agentic_software_review", "code_review_needed", "internal"),
    ("prior_authorization", "prior_auth_needed", "phi_local"),
]


class _DenyEdena:
    """Stand-in for a policy that refuses (used for the containment scenario)."""
    def evaluate_action(self, action) -> EDENADecision:
        return EDENADecision(decision_id="d", action_id=action.action_id, decision="deny",
                             risk_tier="red_blocked", rationale="forced refusal (pilot scenario)")


def _run(example: str, signal_type: str, dc: str, edena, reviewer):
    repo = InMemoryRepository()
    agent = load_agent(EXAMPLES / example / "agent.yaml")
    rt = Runtime(edena, repo=repo, events=EventLog(NullSink()),
                 agents={agent.agent_id: agent}, reviewer=reviewer)
    sig = Signal(signal_id=f"pilot-{example}", source="pilot", signal_type=signal_type,
                 requester=RequesterContext(role="rn"), data_classification=dc)
    with LatencyBudget(POINT_OF_CARE_BUDGET_MS) as budget:
        bundle = rt.run(load_workflow(EXAMPLES / example / "workflow.yaml"), sig)
    route = ModelRouter().route(workflow_run_id=bundle.workflow_run_id,
                                data_classification=dc, risk_tier="yellow")
    return repo, bundle, budget, route


def main() -> int:
    router_local_ok = True
    phi_egress = 0
    rows, ungated = [], 0
    evidence_count, within_budget_all, max_latency = 0, True, 0.0

    for example, stype, dc in WORKFLOWS:
        repo, bundle, budget, route = _run(example, stype, dc, EdenaClient(), AutoApproveReviewer())
        evidence_count += repo.get_evidence(bundle.bundle_id) is not None
        decisions = bundle.edena_decisions
        executed = sum(1 for t in bundle.tool_calls if t.executed)
        ungated += max(0, executed - len(decisions))  # executed tools lacking a decision
        # PHI egress: PHI work must route local; citations must be references.
        if dc == "phi_local" and not route.locality.startswith("local"):
            router_local_ok = False
        phi_egress += sum(1 for c in bundle.source_citations if "/" not in c and ":" not in c)
        within_budget_all &= budget.within_budget
        max_latency = max(max_latency, budget.elapsed_ms or 0.0)
        rows.append((example, [d.risk_tier for d in decisions], bundle.final_action,
                     len(decisions), len(bundle.source_citations), round(budget.elapsed_ms or 0, 1)))

    # Containment scenario — a refused action must block + record an Incident.
    repo_x, bundle_x, _b, _r = _run("icu_handoff", "icu_handoff_needed", "phi_local",
                                    _DenyEdena(), AutoApproveReviewer())
    incidents = repo_x.list_incidents()
    refusal_ok = bool(incidents) and not any(t.executed for t in bundle_x.tool_calls)

    gates = [
        ("Every run produces an EvidenceBundle", evidence_count == len(WORKFLOWS)),
        ("Every consequential action passed EDENA (none ungated)", ungated == 0),
        ("PHI work routed to local models only", router_local_ok),
        ("Zero PHI egress (citations are references, not content)", phi_egress == 0),
        (f"All runs within the {POINT_OF_CARE_BUDGET_MS}ms point-of-care budget", within_budget_all),
        ("Refusal blocks the action and records an Incident", refusal_ok),
    ]
    passed = all(ok for _, ok in gates)

    lines = ["# Florence-X pilot evidence report", "",
             "_Synthetic data, local model route. Generated by `make pilot-report`._", "",
             "## Acceptance gates", "", "| Gate | Result |", "|---|---|"]
    lines += [f"| {label} | {'✅ PASS' if ok else '❌ FAIL'} |" for label, ok in gates]
    lines += ["", "## Per-workflow detail", "",
              "| Workflow | EDENA tiers | Final action | Actions gated | Source refs | Latency (ms) |",
              "|---|---|---|---|---|---|"]
    lines += [f"| {w} | {', '.join(t) or '—'} | {fa} | {n} | {sc} | {lat} |"
              for (w, t, fa, n, sc, lat) in rows]
    lines += ["", (f"Containment scenario: {'✅' if refusal_ok else '❌'} a denied action was "
              f"blocked and recorded incident `{incidents[0].incident_id if incidents else 'none'}` "
              f"(triggered_by={incidents[0].triggered_by if incidents else 'n/a'})."),
              "", (f"Peak run latency: {round(max_latency,1)}ms "
              f"(budget {POINT_OF_CARE_BUDGET_MS}ms)."), "",
              f"**Overall: {'PASS — all acceptance gates met.' if passed else 'FAIL — see gates above.'}**"]

    report = "\n".join(lines) + "\n"
    (ROOT / "pilot-report.md").write_text(report)
    print(report)
    print(f"(wrote {ROOT / 'pilot-report.md'})")
    return 0 if passed else 1


if __name__ == "__main__":
    sys.exit(main())
