"""EvidenceBundle — generated by default on every run. A compliance artifact."""
from __future__ import annotations

from datetime import datetime

from pydantic import Field

from .common import FlorenceModel, utcnow
from .edena_decision import EDENADecision
from .human_review import HumanReview


class ToolCallRecord(FlorenceModel):
    tool_id: str
    action_id: str
    proposed: bool
    executed: bool
    output_hash: str | None = None
    error: str | None = None


class EvidenceBundle(FlorenceModel):
    bundle_id: str
    workflow_run_id: str
    signal_id: str

    context_hash: str | None = None
    model_used: str | None = None
    model_version: str | None = None
    prompt_template_version: str | None = None
    agent_versions: dict = Field(default_factory=dict)

    tool_calls: list[ToolCallRecord] = Field(default_factory=list)
    edena_decisions: list[EDENADecision] = Field(default_factory=list)
    human_reviews: list[HumanReview] = Field(default_factory=list)

    final_action: str | None = None
    source_citations: list[str] = Field(default_factory=list)

    signal_received_at: datetime | None = None
    executed_at: datetime | None = None
    reviewed_at: datetime | None = None
    completed_at: datetime | None = None

    overrides: list[str] = Field(default_factory=list)
    deviations_from_edena: list[str] = Field(default_factory=list)
    incident_flags: list[str] = Field(default_factory=list)
    outcome_feedback: str | None = None
    created_at: datetime = Field(default_factory=utcnow)
