"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-15 12:09:42.681727
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('envelope', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)

    op.create_table('evidence_bundles',
    sa.Column('bundle_id', sa.String(), nullable=False),
    sa.Column('workflow_run_id', sa.String(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('final_action', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('bundle_id')
    )
    with op.batch_alter_table('evidence_bundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_bundles_signal_id'), ['signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_bundles_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('signals',
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('data_classification', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('signal_id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_signal_type'), ['signal_type'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('workflow_run_id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('context_id', sa.String(), nullable=True),
    sa.Column('evidence_bundle_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.signal_id'], ),
    sa.PrimaryKeyConstraint('workflow_run_id')
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('candidate_actions',
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('workflow_run_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('data_classification', sa.String(), nullable=False),
    sa.Column('reversible', sa.Boolean(), nullable=False),
    sa.Column('external_boundary_crossed', sa.Boolean(), nullable=False),
    sa.Column('proposed_payload_hash', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.workflow_run_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    with op.batch_alter_table('candidate_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_actions_workflow_run_id'), ['workflow_run_id'], unique=False)

    op.create_table('edena_decisions',
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('risk_tier', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['candidate_actions.action_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    with op.batch_alter_table('edena_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edena_decisions_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edena_decisions_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_edena_decisions_risk_tier'), ['risk_tier'], unique=False)

    op.create_table('human_reviews',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('reviewer_role', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['candidate_actions.action_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    with op.batch_alter_table('human_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_human_reviews_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_human_reviews_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_human_reviews_outcome'), ['outcome'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_reviews_outcome'))
        batch_op.drop_index(batch_op.f('ix_human_reviews_decision_id'))
        batch_op.drop_index(batch_op.f('ix_human_reviews_action_id'))

    op.drop_table('human_reviews')
    with op.batch_alter_table('edena_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edena_decisions_risk_tier'))
        batch_op.drop_index(batch_op.f('ix_edena_decisions_decision'))
        batch_op.drop_index(batch_op.f('ix_edena_decisions_action_id'))

    op.drop_table('edena_decisions')
    with op.batch_alter_table('candidate_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_actions_workflow_run_id'))

    op.drop_table('candidate_actions')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_status'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_signal_type'))

    op.drop_table('signals')
    with op.batch_alter_table('evidence_bundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_bundles_workflow_run_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_bundles_signal_id'))

    op.drop_table('evidence_bundles')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index(batch_op.f('ix_events_subject'))

    op.drop_table('events')
    # ### end Alembic commands ###
