"""add policy_packs table

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-15 15:39:17.239260
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_packs',
    sa.Column('pack_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('superseded_by', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('pack_id')
    )
    with op.batch_alter_table('policy_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_packs_version'), ['version'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_packs_version'))

    op.drop_table('policy_packs')
    # ### end Alembic commands ###
