/* Node checks and synthetic cross-language snapshots; never user records. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../..');
const engine=require(path.join(root,'apps/learning-workspace/deliberation.js'));
const html=fs.readFileSync(path.join(root,'apps/learning-workspace/index.html'),'utf8');
const data=JSON.parse(html.match(/<script type="application\/json" id="bundle">([\s\S]*?)<\/script>/)[1]);
const v=data.deliberation,ids=v.pack.cases.map(c=>c.case_id);
const digest=x=>crypto.createHash('sha256').update(JSON.stringify(x,function(k,value){return value&&typeof value==='object'&&!Array.isArray(value)?Object.keys(value).sort().reduce((o,key)=>{o[key]=value[key];return o;},{}):value;})).digest('hex');
let passed=0;const snapshots=[];
const test=(name,fn)=>{fn();passed++;console.log('PASS '+name);};
const start=()=>engine.start(v,ids[0]);
const commit=s=>engine.apply(s,v,'commit',{text:'Inspect limits before relying on a resource.',uncertain:false});
const compare=()=>engine.apply(commit(start()),v,'reveal');
const decision=outcome=>({outcome,reason:'The evidence is incomplete.',alternative:'Try a narrower evaluation.',consequence:'Review effort remains necessary.',replacement:outcome==='revise'?'Keep this a draft pending evaluation.':null});
test('JSON bindings match Python canonical fixture digests',()=>{assert.equal(digest(v.pack),v.pack_sha256);v.pack.cases.forEach(c=>assert.equal(digest(c),v.case_digests[c.case_id]));});
test('No default verdict and no early reveal',()=>{const s=start();assert.equal(s.rounds[0].decision,null);assert.throws(()=>engine.apply(s,v,'reveal'));snapshots.push(s);});
test('Commit does not reveal; reveal is separate',()=>{let s=commit(start());assert.equal(s.rounds[0].revealed,false);s=engine.apply(s,v,'reveal');assert.equal(s.rounds[0].revealed,true);snapshots.push(s);});
for(const out of ['accept','revise','reject','withhold'])test(out+' is a learning choice, not permission',()=>{const old=compare(),s=engine.apply(old,v,'choose',decision(out));assert.equal(s.rounds[0].decision.outcome,out);assert.equal(old.rounds[0].decision,null);assert.equal(s.authority,'no_execution_permission');snapshots.push(s);});
test('Explicit uncertainty accepted',()=>{const s=engine.apply(start(),v,'commit',{text:null,uncertain:true});assert.equal(engine.apply(s,v,'reveal').rounds[0].revealed,true);snapshots.push(s);});
test('Empty, oversize, wrong boolean and injected approval refused',()=>{for(const p of [{text:null,uncertain:false},{text:' ',uncertain:false},{text:'x'.repeat(2001),uncertain:false},{text:'ok',uncertain:'false'},{text:'ok',uncertain:false,approval:true}])assert.throws(()=>engine.apply(start(),v,'commit',p));});
test('Revision requires replacement; bad outcomes and extras rejected',()=>{assert.throws(()=>engine.apply(compare(),v,'choose',{...decision('revise'),replacement:null}));assert.throws(()=>engine.apply(compare(),v,'choose',decision('approve')));assert.throws(()=>engine.apply(compare(),v,'choose',{...decision('accept'),execute:true}));});
test('Choice cannot be overwritten; optional reflection once',()=>{let s=engine.apply(compare(),v,'choose',decision('reject'));assert.throws(()=>engine.apply(s,v,'choose',decision('accept')));s=engine.apply(s,v,'reflect',{text:'I would seek direct outcome evidence.'});assert.throws(()=>engine.apply(s,v,'reflect',{text:'overwrite'}));snapshots.push(s);});
for(const reason of ['context_changed','evidence_view_changed'])test(reason+' retains history and invalidates continuation',()=>{let s=engine.apply(compare(),v,'choose',decision('withhold'));const old=JSON.stringify(s.rounds[0].decision);s=engine.apply(s,v,'invalidate',{reason});assert.throws(()=>engine.apply(s,v,'reflect',{text:'late'}));s=engine.apply(s,v,'restart',{case_id:ids[1]});assert.equal(JSON.stringify(s.rounds[0].decision),old);assert.equal(s.rounds[1].initial,null);assert.equal(s.rounds[1].revealed,false);snapshots.push(s);});
test('Pause denies actions; invalidation survives resume',()=>{let s=engine.apply(commit(start()),v,'pause');assert.throws(()=>engine.apply(s,v,'reveal'));s=engine.apply(s,v,'invalidate',{reason:'context_changed'});s=engine.apply(s,v,'pause');assert.throws(()=>engine.apply(s,v,'reveal'));snapshots.push(s);});
test('Restart limit is twelve rounds',()=>{let s=start();for(let i=1;i<12;i++)s=engine.apply(s,v,'restart',{case_id:ids[0]});assert.equal(s.rounds.length,12);assert.throws(()=>engine.apply(s,v,'restart',{case_id:ids[0]}));snapshots.push(s);});
test('Unknown context and changed snapshot denied',()=>{assert.throws(()=>engine.start(v,'missing'));let s=JSON.parse(JSON.stringify(start()));s.rounds[0].case.proposal='edited';assert.throws(()=>engine.check(s,v));});
test('Error does not leak supplied content',()=>{let s=JSON.parse(JSON.stringify(start()));s.secret='PRIVATE_MARKER';assert.throws(()=>engine.check(s,v),e=>e.message==='Invalid or out-of-order practice request; nothing changed.');});
test('Deep snapshots cannot be mutated',()=>{let s=compare();assert.throws(()=>{s.rounds[0].case.proposal='edited';});assert.throws(()=>{s.authority='allowed';});});
console.log(JSON.stringify({passed,failed:0,scope:'Node pure transition tests'}));
if(process.argv[2])fs.writeFileSync(process.argv[2],JSON.stringify(snapshots,null,2)+'\n');
